name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Check and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Run Check
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: detektMainAll check -xdetekt

      - name: Publish
        uses: eskatos/gradle-command-action@v2
        if: github.ref == 'refs/heads/main' && success()
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
